services:
    private:
      build: .
      container_name: lucos_private
      ports: 
        - $PORT:80
      environment:
        - "CLIENT_KEYS"
      volumes:
        - "medlib:/usr/local/private/medlib"
      image: lucas42/lucos_private
      restart: always
      healthcheck:
        test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80/_info"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 15s

volumes:
  medlib:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=aurora.local,rw,nolock,hard,nointr,nfsvers=3"
      device: ":/medlib"