services:
    private:
      build: .
      container_name: lucos_private
      ports: 
        - "8016:80"
      environment:
        - "SECRET_PATH"
        - "CLIENT_KEYS"
      volumes:
        - "medlib:/usr/local/private/medlib"
      image: lucas42/lucos_private
      restart: always

volumes:
  medlib:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=aurora.local,rw,nolock,hard,nointr,nfsvers=3"
      device: ":/medlib"