#!/bin/bash
set -e

if [ -z "$SECRET_PATH" ]; then
    echo "Need to set SECRET_PATH to indicate where mounted files are stored"
    exit 1
fi
if [ ! -e "/usr/local/apache2/htdocs/$SECRET_PATH" ]; then
	ln -s "/usr/local/private" "/usr/local/apache2/htdocs/$SECRET_PATH"
fi

if [ -z "$CLIENT_KEYS" ]; then
    echo "Need to set CLIENT_KEYS (should be auto-generated by lucos_creds)"
    exit 1
fi

HTPASSWD_FILE="/usr/local/apache2/private.htpasswd"
> "$HTPASSWD_FILE"
chown www-data "$HTPASSWD_FILE"
chmod 700 "$HTPASSWD_FILE"

IFS=';' read -ra KEYS <<< "$CLIENT_KEYS"
for systemkey in "${KEYS[@]}"; do
    IFS='=' read -r systemenv key <<< "$systemkey"
    IFS=':' read -r system env <<< "$systemenv"
    htpasswd -nbB "$system" "$key" >> "$HTPASSWD_FILE"
done

httpd-foreground