#!/bin/bash
set -e

if [ -z "$CLIENT_KEYS" ]; then
    echo "Need to set CLIENT_KEYS (should be auto-generated by lucos_creds)"
    exit 1
fi

HTPASSWD_FILE="/usr/local/apache2/private.htpasswd"
> "$HTPASSWD_FILE"
chown www-data "$HTPASSWD_FILE"
chmod 700 "$HTPASSWD_FILE"

IFS=';' read -ra KEYS <<< "$CLIENT_KEYS"
for systemkey in "${KEYS[@]}"; do
    IFS='=' read -r systemenv key <<< "$systemkey"
    IFS=':' read -r system env <<< "$systemenv"
    htpasswd -nbB "$system-$env" "$key" >> "$HTPASSWD_FILE"
done

httpd-foreground